steps:

- id: 'Build Container Image'
- name: 'gcr.io/cloud-builders/docker:latest'
  args: [ 'build', '-t', 'europe-west3-docker.pkg.dev/${PROJECT_ID}/kschieban-reg/cloud-run-hello:${SHORT_SHA}', '.' ]


- id: 'Push Container Image to Container Registry'
  name: 'gcr.io/cloud-builders/docker:latest'
  args: ['push', 'europe-west3-docker.pkg.dev/${PROJECT_ID}/kschieban-reg/cloud-run-hello:${SHORT_SHA}']

- id: 'Deploy to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrun-srv'
  - '--image'
  - 'europe-west3-docker.pkg.dev/${PROJECT_ID}/kschieban-reg/cloud-run-hello:${SHORT_SHA}'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
